### PR TITLE
Added support for local ARM architecture docker builds

### PR DESCRIPTION
**Pull request by mluker**
* Added support for ARM architecture when performing docker builds due to missing gcc libs.
* Chatbot form updates
  * Added support for pressing enter to submit request
  * Made the input field required
  * Added the endpoint name to the output to show where the results originated from

### CODE REVIEW

**Review by martinpeck — COMMENTED** [review]
Both parts of the PR look good to me (I'll let @stuartleeks give approval) but it might have been better to split these two things as they're quite separate.

The first part of this PR is the additional tools in Dockerfile to allow the Python package installation to work on ARM (because some packages don't have wheels for ARM). This looks reasonable. I've tested that this fails on a Ubuntu ARM without the PR changes, and that `docker build` works with the PR changes in place.

I'm also OK with the changes to the web page, but I actually think that the endpoint stuff (live vs simulator) is confusing and should be removed (see #30).

**Comment by mluker** [comment]
@martinpeck I've backed out the form changes and will PR that change separately without the endpoint output.

**Comment by martinpeck** [comment]
Thanks for splitting into 2 PRs @mluker ! 👍

**Comment by stuartleeks** [comment]
Thanks @mluker!

Can you add some context around building for ARM? E.g. are you on a machine with an ARM chip and wanting to build and run the container image locally? Or are you targetting deployment to another environment with ARM chips?

**Comment by stuartleeks** [comment]
Or are you running locally on an ARM chip and trying to deploy to ACA? I just checked and realised that we [don't currently specify the target platform](https://github.com/microsoft/aoai-api-simulator/blob/693fa891923e04b79a0a69b758ecd271a48879ee/scripts/docker-build-and-push.sh#L37) when building the image to deploy to ACA!

**Comment by stuartleeks** [comment]
Ok, cool.

I've added #36 to track the image build for ACA deployment.
I've kicked off the validation build again and raised #33 to track resolving the failing test

**Pull request merged**
